"""Create service requests table

Revision ID: 35b3d86b4aff
Revises: 
Create Date: 2026-10-08 12:06:23.923057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b3d86b4aff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('nature', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('location_type', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('intersection_1', sa.Text(), nullable=True),
    sa.Column('intersection_2', sa.Text(), nullable=True),
    sa.Column('location_error', sa.Text(), nullable=True),
    sa.Column('borough', sa.Text(), nullable=True),
    sa.Column('geographic_borough', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('original_channel', sa.Text(), nullable=True),
    sa.Column('responsible_unit', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('source_file_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_row_number', sa.BigInteger(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_service_requests_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_service_requests_longitude'),
    sa.CheckConstraint('source_row_number > 0', name='ck_service_requests_source_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_requests_borough_created_at', 'service_requests', ['borough', 'created_at'], unique=False)
    op.create_index('ix_service_requests_category_created_at', 'service_requests', ['category', 'created_at'], unique=False)
    op.create_index('ix_service_requests_created_at', 'service_requests', ['created_at'], unique=False)
    op.create_index('ix_service_requests_nature_created_at', 'service_requests', ['nature', 'created_at'], unique=False)
    op.create_index('ix_service_requests_source_id', 'service_requests', ['source_id'], unique=False)
    op.create_index('ux_service_requests_source_file_row', 'service_requests', ['source_file_sha256', 'source_row_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_service_requests_source_file_row', table_name='service_requests')
    op.drop_index('ix_service_requests_source_id', table_name='service_requests')
    op.drop_index('ix_service_requests_nature_created_at', table_name='service_requests')
    op.drop_index('ix_service_requests_created_at', table_name='service_requests')
    op.drop_index('ix_service_requests_category_created_at', table_name='service_requests')
    op.drop_index('ix_service_requests_borough_created_at', table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
